#!/usr/bin/env snakemake

import sys
import pandas as pd

import growpi
shell.executable("bash")


SAMPLES = growpi.parse_samples(config)


include: "../rules/grid.smk"


rule all:
    input:
        rules.grid_all.input
